import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { GitHubData, PersonalityScores } from '../types';

interface ReadmeGeneratorProps {
  data: GitHubData;
  scores: PersonalityScores;
  lang: 'ja' | 'en';
}

export function ReadmeGenerator({ data, scores, lang }: ReadmeGeneratorProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const { user } = data;
  const topLangs = Object.entries(data.languageStats)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 5)
    .map(([name]) => name);

  const readme = `# Hi there 👋 I'm ${user.name ?? user.login}

${user.bio ?? ''}

## 🧬 My Development DNA

- 🌍 ${user.location ?? 'Earth'}
- 💼 ${user.company ?? 'Independent Developer'}
- 📚 ${user.public_repos} public repositories
- ⭐ ${data.repos.reduce((sum, r) => sum + r.stargazers_count, 0)} total stars earned

## 🔬 Top Languages

${topLangs.map(l => `- ${l}`).join('\n')}

## 📊 Personality Scores

| Trait | Score |
|-------|-------|
| Creator | ${scores.creator}/100 |
| Collaborator | ${scores.collaborator}/100 |
| Communicator | ${scores.communicator}/100 |
| Maintainer | ${scores.maintainer}/100 |
| Explorer | ${scores.explorer}/100 |

---
*Generated by [GitHub DNA Visualizer](https://github.com)*
`;

  return (
    <div>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="px-4 py-2 text-sm border border-gh-border text-gh-text rounded-lg hover:border-gh-blue hover:text-gh-blue transition-colors"
      >
        📄 {lang === 'ja' ? 'README生成' : 'Generate README'}
      </button>

      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            className="mt-4 overflow-hidden"
          >
            <div className="bg-gh-bg border border-gh-border rounded-lg p-4">
              <div className="flex items-center justify-between mb-3">
                <span className="text-gh-muted text-sm font-mono">README.md</span>
                <button
                  onClick={() => {
                    navigator.clipboard.writeText(readme)
                      .then(() => {
                        setCopied(true);
                        setTimeout(() => setCopied(false), 2000);
                      })
                      .catch(() => {});
                  }}
                  className="text-xs text-gh-blue hover:underline"
                >
                  {copied ? (lang === 'ja' ? 'コピー済み！' : 'Copied!') : (lang === 'ja' ? 'コピー' : 'Copy')}
                </button>
              </div>
              <pre className="text-gh-text text-xs overflow-auto max-h-64 font-mono whitespace-pre-wrap">
                {readme}
              </pre>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
